asr_sdm_video_enhancement_ml_node:
  ros__parameters:
    input_topic: /camera/camera/color/image_raw
    output_topic: /asr_sdm_video_enhancement_ml/image
    num_threads: 0
    normalize_output: true
